version: '3.8'

services:
  arbitrage-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: sui-arbitrage-bot-template
    container_name: sui-arbitrage-bot-template
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      SIMULATION_ONLY: "true"
      DEMO_MODE: "true"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "node", "/app/dist/utils/health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: sui-arbitrage-bot-template-dev
    container_name: sui-arbitrage-bot-template-dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      SIMULATION_ONLY: "true"
      DEMO_MODE: "true"
    command: npm run dev
