version: '3.8'

services:
  arbitrage-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: sui-arbitrage-bot-template
    container_name: sui-arbitrage-bot-template
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - .env.example
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      SIMULATION_ONLY: "true"
      DEMO_MODE: "true"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
